# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_Saida', models.CharField(choices=[(1, 'Entrada'), (2, 'Saída')], max_length=1)),
                ('configuraçãoHora', models.CharField(choices=[(1, '08:00/13:00'), (2, '08:00/12:00 e 14:00/18:00')], max_length=1)),
                ('dataEHora', models.DateTimeField(blank=True, null=True)),
                ('consistente', models.BooleanField(verbose_name='Consistente')),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cod', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField()),
                ('nomeChef', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(max_length=200)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lpc_evento.Funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lpc_evento.Funcionario'),
        ),
    ]
